services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # CMS Microservice
  cms-microservice:
    build:
      context: .
      dockerfile: cmsmicroservice/Dockerfile
    container_name: ${CMS_CONTAINER_NAME}
    ports:
      - "${CMS_SERVICE_PORT}:8080"
    environment:
      - MANAGEMENT_SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=${CMS_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SERVER_SERVLET_CONTEXT_PATH=${SERVER_SERVLET_CONTEXT_PATH}
      - CMS_AREEBA_CRYPTO_PASSWORD=${CMS_AREEBA_CRYPTO_PASSWORD}
      - CMS_AREEBA_CRYPTO_SALT_HEX=${CMS_AREEBA_CRYPTO_SALT_HEX}
      - FRAUD_URL=${FRAUD_URL}
      - SPRING_FLYWAY_SCHEMAS=${CMS_FLYWAY_SCHEMAS}
      - SPRING_FLYWAY_DEFAULT_SCHEMA=${CMS_FLYWAY_DEFAULT_SCHEMA}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://localhost:8080/cms/v1/actuator/health/readiness || exit 1",
        ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    depends_on:
      postgres:
        condition: service_healthy
      fraud-microservice:
        condition: service_healthy

  # Fraud Microservice
  fraud-microservice:
    build:
      context: .
      dockerfile: fraudmicroservice/Dockerfile
    container_name: ${FRAUD_CONTAINER_NAME}
    ports:
      - "${FRAUD_SERVICE_PORT}:8080"
    environment:
      - MANAGEMENT_SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=${FRAUD_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SERVER_SERVLET_CONTEXT_PATH=${FRAUD_SERVER_SERVLET_CONTEXT_PATH}
      - FRAUD_LIMIT=${FRAUD_LIMIT}
      - FRAUD_INTERVAL=${FRAUD_INTERVAL}
      - SPRING_FLYWAY_SCHEMAS=${FRAUD_FLYWAY_SCHEMAS}
      - SPRING_FLYWAY_DEFAULT_SCHEMA=${FRAUD_FLYWAY_DEFAULT_SCHEMA}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://localhost:8080/fraud/v1/actuator/health/readiness || exit 1",
        ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
