swagger: "2.0"
info:
  title: "Fraud Detection Service"
  version: "1.0.0"
  description: >
    Evaluates transactions for potential fraud based on amount and frequency:
    - Reject if amount > 10,000
    - Reject if ≥ 8 transactions for the same card within the last hour
host: "localhost:8090"
basePath: "/fraud/v1"
schemes: ["https"]
consumes: ["application/json"]
produces: ["application/json"]

tags:
  - name: "Fraud"
    description: "Fraud evaluation endpoints"

paths:
  /evaluate:
    post:
      tags: ["Fraud"]
      summary: "Evaluate a transaction for fraud and record the attempt"
      operationId: evaluateTransaction
      parameters:
        - in: "body"
          name: "fraudCheckRequest"
          required: true
          schema:
            $ref: "#/definitions/FraudCheckRequest"
      responses:
        "200":
          description: "Evaluation result"
          schema:
            $ref: "#/definitions/FraudCheckResponse"
        "400":
          description: "Validation error"
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
  FraudCheckRequest:
    type: "object"
    required: ["cardId", "amount", "timestamp"]
    properties:
      cardId:
        type: "string"
        format: "uuid"
      amount:
        type: "number"
        format: "double"
        example: 1500.00
      timestamp:
        type: "string"
        format: "date-time"
        example: "2025-09-02T09:00:00Z"

  FraudCheckResponse:
    type: "object"
    required: ["approved", "reason"]
    properties:
      approved:
        type: "boolean"
        example: true
      reason:
        type: "string"
        description: "OK, AMOUNT_EXCEEDS_LIMIT, or FREQUENCY_EXCEEDS_LIMIT"
        example: "OK"

  ErrorResponse:
    type: "object"
    properties:
      error:
        type: "string"
        example: "_ERR"